let computerdata = [
  { "model_name": "Acer Swift 5", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "Dell XPS 13", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-1250U", "gpu": "Intel Iris Xe" },
  { "model_name": "HP Spectre x360", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-1240P", "gpu": "Intel Iris Xe" },
  { "model_name": "Apple MacBook Pro 14", "ram": "32GB", "storage": "1TB SSD", "cpu": "Apple M2 Pro", "gpu": "Integrated 19-core GPU" },
  { "model_name": "Lenovo ThinkPad X1 Carbon Gen 10", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "Asus ROG Zephyrus G14", "ram": "32GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 9 6900HS", "gpu": "NVIDIA GeForce RTX 3080" },
  { "model_name": "MSI Stealth 15M", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Razer Blade 15", "ram": "32GB", "storage": "2TB SSD", "cpu": "Intel Core i9-12900H", "gpu": "NVIDIA GeForce RTX 3080 Ti" },
  { "model_name": "Gigabyte Aero 16", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12800H", "gpu": "NVIDIA GeForce RTX 3070 Ti" },
  { "model_name": "Microsoft Surface Laptop 5", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1255U", "gpu": "Intel Iris Xe" },
  { "model_name": "Alienware m15 R7", "ram": "32GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 9 6900HX", "gpu": "NVIDIA GeForce RTX 3070 Ti" },
  { "model_name": "Acer Predator Helios 300", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "HP Omen 16", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12800H", "gpu": "NVIDIA GeForce RTX 3070" },
  { "model_name": "Lenovo Legion 5 Pro", "ram": "16GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 7 6800H", "gpu": "NVIDIA GeForce RTX 3070" },
  { "model_name": "Asus TUF Dash F15", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-12650H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Apple MacBook Air M2", "ram": "16GB", "storage": "512GB SSD", "cpu": "Apple M2", "gpu": "Integrated 10-core GPU" },
  { "model_name": "Samsung Galaxy Book2 Pro", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "LG Gram 16", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "Dell Alienware Aurora R13", "ram": "32GB", "storage": "2TB SSD", "cpu": "Intel Core i9-12900KF", "gpu": "NVIDIA GeForce RTX 3090" },
  { "model_name": "Corsair One i300", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Core i9-12900K", "gpu": "NVIDIA GeForce RTX 3080 Ti" },
  { "model_name": "NZXT Streaming PC", "ram": "32GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 7 5800X", "gpu": "NVIDIA GeForce RTX 3070" },
  { "model_name": "HP Envy Desktop TE01", "ram": "16GB", "storage": "512GB SSD + 1TB HDD", "cpu": "Intel Core i5-12400", "gpu": "NVIDIA GeForce GTX 1660 Super" },
  { "model_name": "Dell Inspiron 3910", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-12400", "gpu": "Intel UHD Graphics 730" },
  { "model_name": "Lenovo IdeaCentre Gaming 5", "ram": "16GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 5 5600G", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Acer Aspire TC-1760", "ram": "12GB", "storage": "512GB SSD", "cpu": "Intel Core i5-12400", "gpu": "Intel UHD Graphics 730" },
  { "model_name": "CyberPowerPC Gamer Xtreme", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700F", "gpu": "NVIDIA GeForce RTX 3060 Ti" },
  { "model_name": "iBUYPOWER SlateMR 291i", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700KF", "gpu": "NVIDIA GeForce RTX 3070" },
  { "model_name": "Skytech Shiva II", "ram": "16GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 5 5600X", "gpu": "NVIDIA GeForce RTX 3060 Ti" },
  { "model_name": "Origin Neuron", "ram": "64GB", "storage": "4TB SSD", "cpu": "Intel Core i9-12900KS", "gpu": "NVIDIA GeForce RTX 3090 Ti" },
  { "model_name": "Maingear Vybe", "ram": "32GB", "storage": "2TB SSD", "cpu": "AMD Ryzen 9 5950X", "gpu": "NVIDIA GeForce RTX 3080" },
  { "model_name": "Falcon Northwest Talon", "ram": "64GB", "storage": "4TB SSD", "cpu": "AMD Ryzen 9 7950X", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Asus ProArt Studiobook 16", "ram": "64GB", "storage": "2TB SSD", "cpu": "AMD Ryzen 9 5900HX", "gpu": "NVIDIA RTX A5000" },
  { "model_name": "MSI Creator Z17", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i9-12900H", "gpu": "NVIDIA GeForce RTX 3080" },
  { "model_name": "HP ZBook Fury 16 G9", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Xeon W-11955M", "gpu": "NVIDIA RTX A3000" },
  { "model_name": "Dell Precision 7760", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Xeon W-11855M", "gpu": "NVIDIA RTX A5000" },
  { "model_name": "Lenovo ThinkStation P360", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i9-12900K", "gpu": "NVIDIA RTX A2000" },
  { "model_name": "Apple Mac Studio", "ram": "64GB", "storage": "2TB SSD", "cpu": "Apple M1 Ultra", "gpu": "Integrated 64-core GPU" },
  { "model_name": "Microsoft Surface Studio 2+", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-11370H", "gpu": "NVIDIA GeForce RTX 3060 Laptop" },
  { "model_name": "Asus ExpertBook B9", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "Samsung Galaxy Book Odyssey", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-11800H", "gpu": "NVIDIA GeForce RTX 3050 Ti" },
  { "model_name": "Acer Chromebook Spin 713", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Core i5-1135G7", "gpu": "Intel Iris Xe" },
  { "model_name": "Lenovo IdeaPad Flex 5", "ram": "8GB", "storage": "512GB SSD", "cpu": "AMD Ryzen 5 5500U", "gpu": "AMD Radeon Graphics" },
  { "model_name": "HP Pavilion 15", "ram": "8GB", "storage": "512GB SSD", "cpu": "Intel Core i5-1240P", "gpu": "Intel Iris Xe" },
  { "model_name": "Dell G15", "ram": "16GB", "storage": "512GB SSD", "cpu": "AMD Ryzen 7 5800H", "gpu": "NVIDIA GeForce RTX 3050 Ti" },
  { "model_name": "Asus VivoBook Pro 16X", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3050" },
  { "model_name": "MSI Katana GF66", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Gigabyte G5", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-12500H", "gpu": "NVIDIA GeForce RTX 3050 Ti" },
  { "model_name": "Apple iMac 24-inch", "ram": "16GB", "storage": "512GB SSD", "cpu": "Apple M1", "gpu": "Integrated 8-core GPU" },
  { "model_name": "Dell OptiPlex 7090", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-11700", "gpu": "Intel UHD Graphics 750" },
  { "model_name": "HP Elite Mini 800 G9", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700", "gpu": "Intel UHD Graphics 770" },
  { "model_name": "Intel NUC 12 Extreme", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i9-12900", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Acer Veriton X", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Core i3-12100", "gpu": "Intel UHD Graphics 730" },
  { "model_name": "Lenovo ThinkCentre M90q Gen 3", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-12400T", "gpu": "Intel UHD Graphics 730" },
  { "model_name": "HP ProDesk 400 G9", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Core i5-12500", "gpu": "Intel UHD Graphics 770" },
  { "model_name": "Dell Vostro 3910", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-12400", "gpu": "Intel UHD Graphics 730" },
  { "model_name": "Asus Mini PC PN64", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "MSI Cubi N JSL", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Pentium Silver N6000", "gpu": "Intel UHD Graphics" },
  { "model_name": "Gigabyte Brix Pro", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1165G7", "gpu": "Intel Iris Xe" },
  { "model_name": "Apple Mac Mini M2", "ram": "16GB", "storage": "512GB SSD", "cpu": "Apple M2", "gpu": "Integrated 10-core GPU" },
  { "model_name": "Intel NUC 11 Pro", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-1135G7", "gpu": "Intel Iris Xe" },
  { "model_name": "Shuttle XPC Slim DS20U", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Celeron 5205U", "gpu": "Intel UHD Graphics" },
  { "model_name": "Acer Chromebook 516 GE", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Core i5-1240P", "gpu": "Intel Iris Xe" },
  { "model_name": "HP Chromebook x360 14c", "ram": "8GB", "storage": "128GB SSD", "cpu": "Intel Core i3-1115G4", "gpu": "Intel UHD Graphics" },
  { "model_name": "Lenovo Chromebook Duet 5", "ram": "8GB", "storage": "128GB eMMC", "cpu": "Qualcomm Snapdragon 7c Gen 2", "gpu": "Adreno 618" },
  { "model_name": "Samsung Galaxy Chromebook 2", "ram": "8GB", "storage": "128GB SSD", "cpu": "Intel Core i3-10110U", "gpu": "Intel UHD Graphics" },
  { "model_name": "Asus Chromebook CX9", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1165G7", "gpu": "Intel Iris Xe" },
  { "model_name": "Framework Laptop 13", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1260P", "gpu": "Intel Iris Xe" },
  { "model_name": "System76 Lemur Pro", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-1250U", "gpu": "Intel Iris Xe" },
  { "model_name": "Purism Librem 14", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-10710U", "gpu": "Intel UHD Graphics" },
  { "model_name": "TUXEDO Pulse 15", "ram": "32GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 7 5800H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Star Labs StarBook Mk V", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i3-1220P", "gpu": "Intel Iris Xe" },
  { "model_name": "Acer Aspire 5", "ram": "8GB", "storage": "512GB SSD", "cpu": "AMD Ryzen 5 5500U", "gpu": "AMD Radeon Graphics" },
  { "model_name": "HP 17 Laptop", "ram": "8GB", "storage": "256GB SSD", "cpu": "Intel Core i3-1115G4", "gpu": "Intel UHD Graphics" },
  { "model_name": "Dell Latitude 7430", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-1265U", "gpu": "Intel Iris Xe" },
  { "model_name": "Lenovo Yoga Slim 7i Pro", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "Intel Iris Xe" },
  { "model_name": "Samsung Galaxy Book3 Ultra", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-13700H", "gpu": "NVIDIA GeForce RTX 4070" },
  { "model_name": "Asus ZenBook Pro Duo 15", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i9-12900H", "gpu": "NVIDIA GeForce RTX 3070 Ti" },
  { "model_name": "MSI Raider GE76", "ram": "32GB", "storage": "2TB SSD", "cpu": "Intel Core i9-12900HK", "gpu": "NVIDIA GeForce RTX 3080 Ti" },
  { "model_name": "Gigabyte AORUS 17", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3070 Ti" },
  { "model_name": "Alienware x17 R2", "ram": "32GB", "storage": "2TB SSD", "cpu": "Intel Core i9-12900HK", "gpu": "NVIDIA GeForce RTX 3080 Ti" },
  { "model_name": "Razer Blade 18", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Core i9-13980HX", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Acer Nitro 5", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i7-12650H", "gpu": "NVIDIA GeForce RTX 3050 Ti" },
  { "model_name": "HP Victus 15", "ram": "16GB", "storage": "512GB SSD", "cpu": "AMD Ryzen 5 6600H", "gpu": "NVIDIA GeForce RTX 3050" },
  { "model_name": "Dell G16", "ram": "16GB", "storage": "1TB SSD", "cpu": "Intel Core i7-12700H", "gpu": "NVIDIA GeForce RTX 3060" },
  { "model_name": "Lenovo LOQ 15", "ram": "16GB", "storage": "512GB SSD", "cpu": "Intel Core i5-13420H", "gpu": "NVIDIA GeForce RTX 4050" },
  { "model_name": "Asus ROG Strix Scar 17", "ram": "32GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 9 7945HX", "gpu": "NVIDIA GeForce RTX 4080" },
  { "model_name": "MSI Titan GT77", "ram": "128GB", "storage": "4TB SSD", "cpu": "Intel Core i9-13980HX", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Gigabyte AORUS 15X", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i9-13900HX", "gpu": "NVIDIA GeForce RTX 4070" },
  { "model_name": "Alienware Aurora R15", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Core i9-13900KF", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Corsair Vengeance i7400", "ram": "32GB", "storage": "2TB SSD", "cpu": "Intel Core i7-13700K", "gpu": "NVIDIA GeForce RTX 4080" },
  { "model_name": "NZXT Player: Two", "ram": "16GB", "storage": "1TB SSD", "cpu": "AMD Ryzen 7 7700X", "gpu": "NVIDIA GeForce RTX 4070 Ti" },
  { "model_name": "Skytech Chronos", "ram": "32GB", "storage": "1TB SSD", "cpu": "Intel Core i7-13700KF", "gpu": "NVIDIA GeForce RTX 4070" },
  { "model_name": "iBUYPOWER RDY Y40BG201", "ram": "32GB", "storage": "2TB SSD", "cpu": "AMD Ryzen 9 7900X", "gpu": "NVIDIA GeForce RTX 4080" },
  { "model_name": "Origin Millennium", "ram": "128GB", "storage": "8TB SSD", "cpu": "Intel Core i9-13900KS", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Maingear Turbo", "ram": "64GB", "storage": "4TB SSD", "cpu": "AMD Ryzen 9 7950X3D", "gpu": "NVIDIA GeForce RTX 4090" },
  { "model_name": "Falcon Northwest FragBox", "ram": "64GB", "storage": "2TB SSD", "cpu": "Intel Core i9-13900KF", "gpu": "NVIDIA GeForce RTX 4080" },
  { "model_name": "Dell Precision 7875 Tower", "ram": "128GB", "storage": "8TB SSD", "cpu": "AMD Ryzen Threadripper PRO 5975WX", "gpu": "NVIDIA RTX A6000" },
  { "model_name": "HP Z8 Fury G5", "ram": "256GB", "storage": "16TB SSD", "cpu": "Intel Xeon w9-3495X", "gpu": "NVIDIA RTX 6000 Ada" },
  { "model_name": "Lenovo ThinkStation P7", "ram": "128GB", "storage": "8TB SSD", "cpu": "Intel Xeon W7-2495X", "gpu": "NVIDIA RTX A6000" },
  { "model_name": "Apple Mac Pro 2023", "ram": "192GB", "storage": "8TB SSD", "cpu": "Apple M2 Ultra", "gpu": "Integrated 76-core GPU" },
  { "model_name": "Asus ProArt Station PD5", "ram": "64GB", "storage": "4TB SSD", "cpu": "Intel Core i9-12900K", "gpu": "NVIDIA RTX A4000" }

]
